import {generateAPIExportGlueCode} from "@anio-software/enkore-private.target-js-factory"
import {getTargetIntegrationAPIMethodNames} from "@anio-software/enkore-private.target-js-factory/targetIntegration"
import {getProjectAPIMethodNames} from "@anio-software/enkore-private.target-js-factory/project"
import {getAutogenerateAPIMethodNames} from "@anio-software/enkore-private.target-js-factory/autogenerate"

import {defineConfig, defineAutogeneratedFile} from "@anio-software/enkore"
import {defineTargetJSConfig} from "@anio-software/enkore.target-js"

const isPublicRelease = (
	process.env?.RELEASE_VERSION ?? ""
).startsWith("vp")

export const config: unknown = defineConfig({
	target: {
		name: "js",
		options: defineTargetJSConfig({
			_disableRuntimeCodeInjection: true,

			environment: [],

			exports: {
				"targetIntegrationAPI": {
					checkAgainstInterface: [
						"@anio-software/enkore-private.spec",
						"EnkoreTargetIntegrationAPI_V0_Rev0"
					]
				}
			},

			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware",
				tag: isPublicRelease ? "latest" : "canary"
			}]
		})
	},

	autogeneratedFiles: [
		defineAutogeneratedFile({
			destinationPath: `project/export/targetIntegrationAPI/__aggregatedExports.ts`,
			generator() {
				let code = ``

				code += `import {generateTargetIntegrationAPI} from "@anio-software/enkore-private.target-js-factory/targetIntegration"\n`
				code += `import type {EnkoreTargetIntegrationAPI_V0_Rev0 as API} from "@anio-software/enkore-private.spec"\n`

				code += `const api = await generateTargetIntegrationAPI();\n`

				code += generateAPIExportGlueCode(
					"API", "api", getTargetIntegrationAPIMethodNames()
				)

				return code
			}
		}),

		defineAutogeneratedFile({
			destinationPath: `project/export/project/__aggregatedExports.ts`,
			generator() {
				let code = ``

				code += `import {generateProjectAPI} from "@anio-software/enkore-private.target-js-factory/project"\n`
				code += `import type {EnkoreTargetJSProjectAPI_V0_Rev0 as API} from "@anio-software/enkore-private.spec"\n`

				code += `const api = await generateProjectAPI(["inferFromCLIArgs"]);\n`

				code += generateAPIExportGlueCode(
					"API", "api", getProjectAPIMethodNames()
				)

				return code
			}
		}),

		defineAutogeneratedFile({
			destinationPath: `project/export/autogenerate/__aggregatedExports.ts`,
			generator() {
				let code = ``

				code += `import {generateAutogenerateAPI} from "@anio-software/enkore-private.target-js-factory/autogenerate"\n`
				code += `import type {EnkoreTargetJSAutogenerateAPI_V0_Rev0 as API} from "@anio-software/enkore-private.spec"\n`

				code += `const api = await generateAutogenerateAPI();\n`

				code += generateAPIExportGlueCode(
					"API", "api", getAutogenerateAPIMethodNames()
				)

				return code
			}
		})
	]
})
